export const mockRunResponse = {
  job_id: 'mock-job-123',
}

export const mockStatusResponse = {
  status: 'running',
  stage: 1,
  stage_name: 'Repository scan',
  message: 'Cloned github.com/acme/storefront — 847 files indexed',
  elapsed_seconds: 0,
}

let mockStage = 1

export const getMockStatus = () => {
  if (mockStage < 6) mockStage++
  const stages = [
    { stage: 1, stage_name: 'Repository scan',       message: 'Cloned github.com/acme/storefront — 847 files indexed' },
    { stage: 2, stage_name: 'Code analysis',          message: 'Detected FastAPI · SQLAlchemy · Redis · Celery' },
    { stage: 3, stage_name: 'Behaviour extraction',   message: '12 API routes · 3.2 avg DB calls per request' },
    { stage: 4, stage_name: 'Load simulation',         message: 'Peak RPS: 17.4 · DB connections needed: 45' },
    { stage: 5, stage_name: 'Architecture decision',   message: 'AI architect: recommending t3.medium + db.r5.large' },
    { stage: 6, stage_name: 'IaC generation',          message: 'Terraform generated · 8 resources · est. $142/mo' },
  ]
  const current = stages[mockStage - 1]
  return {
    status: mockStage >= 6 ? 'done' : 'running',
    stage: mockStage,
    stage_name: current.stage_name,
    message: current.message,
    elapsed_seconds: mockStage * 18,
  }
}

export const resetMockStage = () => { mockStage = 1 }

export const mockReportResponse = {
  meta: { repo: 'github.com/acme/storefront', language: 'Python', framework: 'FastAPI' },
  structure: {
    total_routes: 14,
    protected_routes: 11,
    has_background_workers: true,
    worker_library: 'Celery',
  },
  compute: {
    profile: 'io_bound',
    avg_cpu_ms_per_request: 12,
    memory_mb_per_request: 8,
    heavy_functions: ['process_order', 'generate_report'],
  },
  database: {
    type: 'PostgreSQL',
    orm: 'SQLAlchemy',
    avg_calls_per_request: 3.2,
    read_write_ratio: 0.75,
    has_transactions: true,
    raw_sql_detected: false,
  },
  cache: { client: 'Redis', pattern: 'read_through' },
  security: {
    risk_score: 3,
    findings_count: 2,
    needs_waf: false,
    needs_secrets_manager: true,
    needs_vpc_private_subnet: true,
    top_risks: [
      {
        severity: 'high',
        issue: 'Hardcoded database password in settings.py',
        fix: 'Move credentials to AWS Secrets Manager and load at runtime via boto3.',
      },
      {
        severity: 'medium',
        issue: 'No rate limiting on /api/checkout endpoint',
        fix: 'Add slowapi middleware or an ALB WAF rule limiting to 20 req/s per IP.',
      },
    ],
  },
}

export const mockRecommendationResponse = {
  services: {
    ec2: {
      instance_type: 't3.medium',
      count: 2,
      asg_min: 1,
      asg_max: 4,
      monthly_usd: 60.74,
      reasoning: 'IO-bound workload fits t3 burst profile. 2 baseline instances cover p99 with 35% headroom at 10k users.',
    },
    rds_compute: {
      instance_type: 'db.t3.medium',
      multi_az: true,
      monthly_usd: 38.40,
      reasoning: 'Moderate query volume (3.2 calls/req). Multi-AZ ensures failover under 60s for production SLA.',
    },
    rds_storage: {
      gb: 80,
      iops: 3000,
      type: 'gp3',
      monthly_usd: 9.28,
    },
    rds_connections: {
      max_connections: 150,
      needs_proxy: false,
      monthly_usd: 0,
    },
    elasticache: {
      node_type: 'cache.t3.micro',
      memory_gb: 0.5,
      monthly_usd: 13.68,
      reasoning: 'Read-through cache absorbs ~68% of DB reads. cache.t3.micro sufficient at 10k users.',
    },
    s3: {
      storage_gb: 200,
      storage_class: 'STANDARD_IA',
      monthly_usd: 4.60,
      reasoning: 'Infrequent-access tier for static assets and order exports.',
    },
    alb: {
      monthly_usd: 18.45,
      reasoning: 'ALB handles SSL termination and forwards to EC2 ASG target group.',
    },
  },
  total_monthly_usd: 145.15,
  estimate_low_usd: 122.00,
  estimate_high_usd: 180.00,
  bottleneck_warnings: [
    'RDS connection pool may saturate above 400 concurrent users — monitor pg_stat_activity and consider PgBouncer.',
    'Celery worker queue depth will spike during order bursts — add a second worker node and SQS visibility timeout tuning.',
  ],
}

export const mockIaCResponse = {
  terraform_hcl: `# Generated by Strikeloop — github.com/acme/storefront
# Estimated cost: $145.15/mo  |  8 resources

terraform {
  required_providers {
    aws = { source = "hashicorp/aws", version = "~> 5.0" }
  }
}

provider "aws" {
  region = var.aws_region
}

variable "aws_region" { default = "us-east-1" }
variable "db_password" { sensitive = true }

# ── Launch template ───────────────────────────────────────────
resource "aws_launch_template" "app" {
  name_prefix   = "storefront-"
  image_id      = "ami-0c55b159cbfafe1f0"
  instance_type = "t3.medium"

  user_data = base64encode(<<-EOF
    #!/bin/bash
    cd /app && uvicorn main:app --host 0.0.0.0 --port 8000
  EOF
  )

  tag_specifications {
    resource_type = "instance"
    tags = { Name = "storefront-app" }
  }
}

# ── Auto Scaling Group ────────────────────────────────────────
resource "aws_autoscaling_group" "app" {
  desired_capacity    = 2
  min_size            = 1
  max_size            = 4
  vpc_zone_identifier = var.private_subnet_ids

  launch_template {
    id      = aws_launch_template.app.id
    version = "$Latest"
  }

  target_group_arns = [aws_lb_target_group.app.arn]
}

# ── Application Load Balancer ─────────────────────────────────
resource "aws_lb" "app" {
  name               = "storefront-alb"
  internal           = false
  load_balancer_type = "application"
  subnets            = var.public_subnet_ids
}

resource "aws_lb_target_group" "app" {
  port     = 8000
  protocol = "HTTP"
  vpc_id   = var.vpc_id
}

# ── RDS PostgreSQL ────────────────────────────────────────────
resource "aws_db_instance" "postgres" {
  identifier        = "storefront-db"
  engine            = "postgres"
  engine_version    = "16.2"
  instance_class    = "db.t3.medium"
  allocated_storage = 80
  storage_type      = "gp3"
  iops              = 3000
  multi_az          = true
  username          = "storefront"
  password          = var.db_password
  skip_final_snapshot = false
}

# ── ElastiCache Redis ─────────────────────────────────────────
resource "aws_elasticache_cluster" "redis" {
  cluster_id           = "storefront-cache"
  engine               = "redis"
  node_type            = "cache.t3.micro"
  num_cache_nodes      = 1
  parameter_group_name = "default.redis7"
  port                 = 6379
}
`,
  filename: 'main.tf',
  resources_count: 8,
  estimated_cost_usd: 145.15,
}

export const mockPlan = {
  resources_to_create: 8,
  resources_to_modify: 0,
  resources_to_destroy: 0,
  current_monthly_usd: 0,
  proposed_monthly_usd: 145,
  cost_delta_usd: 145,
  reasoning: 'Your application runs an io_bound FastAPI workload with PostgreSQL and Redis. At 10,000 users generating 50 requests per day, peak load reaches 17.4 RPS with 45 concurrent DB connections. Two t3.medium EC2 instances behind an ALB provide fault tolerance without over-provisioning. A db.t3.medium RDS instance handles the query volume comfortably with gp3 storage. ElastiCache reduces read pressure by ~60%. This configuration keeps cost at $145/month while leaving room to scale — the ASG grows to 4 instances automatically if traffic doubles.',
  resources: [
    { name: 'aws_launch_template.app',         action: 'create', description: 'EC2 launch template — t3.medium, Amazon Linux 2023' },
    { name: 'aws_autoscaling_group.app',        action: 'create', description: 'Auto scaling group, 1–4 × t3.medium, target tracking policy' },
    { name: 'aws_lb.app',                       action: 'create', description: 'Application Load Balancer, internet-facing, multi-AZ' },
    { name: 'aws_lb_listener.https',            action: 'create', description: 'HTTPS listener on port 443, forwards to target group' },
    { name: 'aws_lb_target_group.app',          action: 'create', description: 'Target group on port 8000, HTTP health check at /healthz' },
    { name: 'aws_db_instance.postgres',         action: 'create', description: 'PostgreSQL 16.2, db.t3.medium, Multi-AZ, 80 GB gp3' },
    { name: 'aws_elasticache_cluster.redis',    action: 'create', description: 'Redis 7, cache.t3.micro, single node, port 6379' },
    { name: 'aws_s3_bucket.assets',             action: 'create', description: 'S3 bucket for static assets and order exports, STANDARD_IA' },
  ],
}

// Deterministic realistic traffic pattern over 24h
const HOURLY_RPS = [48, 32, 28, 22, 35, 82, 210, 420, 610, 780, 847, 910, 875, 820, 760, 710, 680, 740, 820, 870, 790, 610, 380, 180]
// Realistic 30-day daily spend pattern
const DAILY_SPEND = [4.2,4.8,5.1,4.9,5.3,6.1,6.4,5.8,5.6,5.4,5.9,6.2,6.0,5.7,5.5,5.8,6.3,6.7,6.5,6.1,5.9,6.0,6.4,6.8,6.6,6.3,6.1,6.4,6.7,6.84]
// Per-service sparklines (20 points each, deterministic)
const mkSeries = (base, variance, len = 20) =>
  Array.from({ length: len }, (_, i) => {
    const s = Math.sin(i * 0.6) * variance
    const c = Math.cos(i * 0.4) * (variance * 0.5)
    return Math.max(0, Math.round((base + s + c) * 10) / 10)
  })

export const mockLiveResponse = {
  health: 'healthy',
  rps: 847,
  p99_latency_ms: 124,
  error_rate_pct: 0.12,
  active_instances: 2,
  services: {
    ec2:         { cpu_pct: 34, ram_pct: 61,  series: mkSeries(34, 8) },
    rds:         { cpu_pct: 22, connections: 87, iops: 1240, series: mkSeries(87, 15) },
    elasticache: { memory_pct: 41, hit_rate_pct: 94.3, series: mkSeries(94.3, 2) },
    alb:         { rps: 847, '5xx_count': 3,  series: mkSeries(847, 120) },
    sqs:         { queue_depth: 12,            series: mkSeries(12, 6) },
  },
  cost: {
    today_usd: 6.84,
    month_to_date_usd: 89.20,
    forecast_usd: 145.00,
    by_service: { EC2: 38.40, RDS: 47.68, ElastiCache: 13.68, ALB: 18.45, S3: 4.60 },
    daily_last_30: DAILY_SPEND.map((usd, i) => ({
      date: new Date(Date.now() - (29 - i) * 86400000).toISOString().split('T')[0],
      usd,
    })),
  },
  traffic: {
    by_hour: HOURLY_RPS.map((rps, i) => ({
      hour: i,
      label: `${String(i).padStart(2, '0')}:00`,
      rps,
      latency: Math.round(80 + (rps / 847) * 120),
    })),
    top_endpoints: [
      { path: '/api/products',  rps: 312, p99_ms:  88, method: 'GET'  },
      { path: '/api/cart',      rps: 201, p99_ms: 142, method: 'POST' },
      { path: '/api/checkout',  rps:  87, p99_ms: 310, method: 'POST' },
      { path: '/api/orders',    rps:  64, p99_ms:  95, method: 'GET'  },
      { path: '/api/inventory', rps:  41, p99_ms:  72, method: 'GET'  },
    ],
  },
  agent_proposals: [
    {
      id: 'prop-001',
      action: 'Scale EC2 ASG max from 4 → 6 before weekend peak',
      reasoning: 'Traffic history shows 40% spike Saturday 14:00–18:00 UTC. Current max of 4 instances saturated last weekend.',
      cost_delta_usd: 18.40,
      urgency: 'medium',
    },
    {
      id: 'prop-002',
      action: 'Enable RDS Performance Insights',
      reasoning: 'Query latency has increased 18% over the past 7 days. Performance Insights would identify slow queries before they degrade user experience.',
      cost_delta_usd: 7.20,
      urgency: 'low',
    },
  ],
}
